"""
Report Compiler Agent — compiles conversation into HTML+PDF report and emails it.
"""
import json
from datetime import datetime, timezone
from io import BytesIO
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from config import settings
from logger import get_logger, log_action

logger = get_logger("report_compiler")


# ─── PDF Generator ────────────────────────────────────────────────────────────
def _generate_pdf(report: dict, profile: dict) -> bytes:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.units import mm
    from reportlab.lib import colors
    from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer,
                                    Table, TableStyle, HRFlowable)

    buf = BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4,
                            leftMargin=20*mm, rightMargin=20*mm,
                            topMargin=20*mm, bottomMargin=20*mm)

    PURPLE = colors.HexColor("#6366f1")
    DARK   = colors.HexColor("#1e1b4b")
    MUTED  = colors.HexColor("#6b7280")

    styles = getSampleStyleSheet()
    h1 = ParagraphStyle("h1", parent=styles["Heading1"],
                         fontSize=18, textColor=DARK, spaceAfter=4)
    h2 = ParagraphStyle("h2", parent=styles["Heading2"],
                         fontSize=13, textColor=PURPLE, spaceBefore=12, spaceAfter=4)
    body = ParagraphStyle("body", parent=styles["Normal"],
                           fontSize=9.5, leading=14, spaceAfter=6)
    muted = ParagraphStyle("muted", parent=styles["Normal"],
                            fontSize=8, textColor=MUTED, spaceAfter=4)

    story = []

    # Header
    story.append(Paragraph("🏦 AI Loan &amp; Credit Advisor", h1))
    story.append(Paragraph(f"Personal Financial Advisory Report", h2))
    now_str = datetime.now(timezone.utc).strftime("%B %d, %Y at %I:%M %p UTC")
    story.append(Paragraph(f"Prepared for: <b>{profile.get('full_name', 'User')}</b> | {now_str}", muted))
    story.append(HRFlowable(width="100%", thickness=1, color=PURPLE, spaceAfter=8))

    # Financial Snapshot
    if profile.get("annual_income"):
        story.append(Paragraph("Financial Snapshot", h2))
        snap_data = [["Field", "Value"]]
        fields = [
            ("Annual Income", f"₹{profile.get('annual_income', 0):,.0f}"),
            ("Credit Score", str(profile.get("credit_score", "—"))),
            ("Employment", f"{profile.get('employment_months', '—')} months"),
            ("Current EMI", f"₹{profile.get('existing_emi_amount', 0):,.0f}/month"),
            ("City", profile.get("city", "—")),
        ]
        snap_data.extend(fields)
        t = Table(snap_data, colWidths=[70*mm, 90*mm])
        t.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), PURPLE),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("FONTSIZE", (0, 0), (-1, -1), 9),
            ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.HexColor("#f8f8ff"), colors.white]),
            ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e0e0e0")),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ]))
        story.append(t)
        story.append(Spacer(1, 8))

    # Report Sections
    for section in report.get("sections", []):
        story.append(Paragraph(section["title"], h2))
        for para in section.get("content", "").split("\n"):
            if para.strip():
                story.append(Paragraph(para.strip(), body))
        story.append(Spacer(1, 4))

    # Disclaimer
    story.append(HRFlowable(width="100%", thickness=0.5, color=MUTED, spaceAfter=6))
    story.append(Paragraph(
        "This report is generated by AI and is for informational purposes only. "
        "It does not constitute financial advice. Always consult a certified financial advisor.",
        muted))

    doc.build(story)
    return buf.getvalue()


# ─── HTML Email Builder ───────────────────────────────────────────────────────
def _build_html(report: dict, profile: dict) -> str:
    name = profile.get("full_name", "User")
    date = datetime.now(timezone.utc).strftime("%B %d, %Y")
    sections_html = ""
    for s in report.get("sections", []):
        content_html = "".join(
            f'<p style="color:#c7d2fe;font-size:0.88rem;line-height:1.7;margin:4px 0;">{p}</p>'
            for p in s.get("content", "").split("\n") if p.strip()
        )
        sections_html += f"""
        <div style="margin-bottom:24px;">
          <h3 style="color:#a5b4fc;font-size:1rem;margin:0 0 8px;
                     border-left:3px solid #6366f1;padding-left:10px;">{s['title']}</h3>
          {content_html}
        </div>"""

    income_row = ""
    if profile.get("annual_income"):
        income_row = f"""
        <div style="display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin:16px 0;">
          {''.join(f'''<div style="background:rgba(99,102,241,0.1);border:1px solid rgba(99,102,241,0.2);
                            border-radius:8px;padding:10px;text-align:center;">
            <div style="color:#6b7280;font-size:0.7rem;margin-bottom:3px;">{k}</div>
            <div style="color:#e0e7ff;font-weight:700;font-size:0.95rem;">{v}</div></div>'''
                   for k, v in [
                       ("Annual Income", f"₹{profile.get('annual_income',0):,.0f}"),
                       ("Credit Score", str(profile.get("credit_score","—"))),
                       ("Current EMI", f"₹{profile.get('existing_emi_amount',0):,.0f}/mo"),
                   ])}
        </div>"""

    return f"""<!DOCTYPE html>
<html><head><meta charset="utf-8"></head>
<body style="font-family:'Segoe UI',Arial,sans-serif;background:#0f0f1a;margin:0;padding:20px;">
<div style="max-width:680px;margin:0 auto;background:linear-gradient(135deg,#1a1a2e,#16213e);
     border-radius:16px;overflow:hidden;border:1px solid rgba(99,102,241,0.3);">
  <div style="background:linear-gradient(135deg,#6366f1,#a855f7);padding:28px 32px;">
    <div style="font-size:2rem;">🏦</div>
    <h1 style="color:#fff;margin:8px 0 4px;font-size:1.5rem;">AI Loan &amp; Credit Advisor</h1>
    <p style="color:rgba(255,255,255,0.8);margin:0;font-size:0.85rem;">
      Personal Financial Advisory Report · {date}
    </p>
  </div>
  <div style="padding:32px;">
    <p style="color:#e0e7ff;font-size:1rem;margin:0 0 4px;">Hi <b>{name}</b>,</p>
    <p style="color:rgba(199,210,254,0.7);font-size:0.88rem;margin:0 0 20px;">
      Here's your detailed advisory report. A PDF copy is attached to this email.
    </p>
    {income_row}
    <hr style="border:none;border-top:1px solid rgba(255,255,255,0.08);margin:20px 0;">
    {sections_html}
    <hr style="border:none;border-top:1px solid rgba(255,255,255,0.08);margin:20px 0;">
    <p style="color:rgba(199,210,254,0.35);font-size:0.72rem;line-height:1.5;">
      This report is AI-generated for informational purposes only. 
      It does not constitute financial advice.
    </p>
  </div>
</div>
</body></html>"""


# ─── Groq Report Compiler ─────────────────────────────────────────────────────

_LOAN_TYPES = {"home_loan", "personal_loan", "car_loan", "business_loan",
               "education_loan", "gold_loan", "mudra_loan"}
_POLICY_KW  = ["pmay", "mudra", "scheme", "subsidy", "rbi", "policy",
               "eligib", "section 80", "tax", "npa"]


def _classify_topic(topic: str | None) -> str:
    """Return 'loan', 'policy', or 'general' based on topic string."""
    if not topic:
        return "general"
    t = topic.lower()
    if any(lt.replace("_", " ") in t or lt in t for lt in _LOAN_TYPES):
        return "loan"
    if any(kw in t for kw in _POLICY_KW):
        return "policy"
    # "50 lakhs", "home loan eligibility" etc.
    if any(w in t for w in ["lakh", "loan", "emi", "eligib", "crore", "interest"]):
        return "loan"
    return "general"


def _build_prompt(conv_text: str, profile_text: str, state_extras: str,
                  topic: str | None, report_class: str) -> str:
    """Build a topic-specific Groq prompt with distinct section schemas."""

    if report_class == "loan":
        # ── Loan-Specific Report ──────────────────────────────────────────────
        loan_data = ""
        cp = (state_extras or "")
        return f"""You are a senior Indian banking credit analyst writing a formal loan eligibility report.

USER PROFILE: {profile_text}
AGENT ANALYSIS DATA: {cp}
FULL CONVERSATION:
{conv_text}

REPORT FOCUS: {topic or 'Home Loan Eligibility Analysis'}

Write a DETAILED LOAN ANALYSIS REPORT with these EXACT sections (return as JSON):
{{
  "title": "Loan Eligibility Report — [loan type and amount from conversation]",
  "sections": [
    {{
      "title": "🏦 Loan Eligibility Verdict",
      "content": "Clear YES/NO/CONDITIONAL verdict. State the approved loan amount, recommended bank, and one-line reason. Example: ELIGIBLE — ₹50,00,000 Home Loan approved. Recommended lender: SBI at 7.6% p.a."
    }},
    {{
      "title": "📊 Credit & Risk Analysis",
      "content": "Detailed breakdown: Credit Score, Risk Tier, DTI Ratio, Max EMI Capacity, Income-to-Loan ratio, LTV ratio. Include what each metric means for THIS specific loan application."
    }},
    {{
      "title": "💰 Bank-wise Loan Comparison",
      "content": "Detailed table-style comparison of each bank option discussed: Bank name | Interest Rate | EMI/month | Total Interest | Total Cost | Tenure. Include pros/cons of each option. State the recommended option and WHY."
    }},
    {{
      "title": "📉 EMI Affordability Analysis",
      "content": "Monthly EMI vs income analysis. What % of monthly income goes to EMI. Recommended EMI range. Buffer amount remaining after EMI. Impact on lifestyle and savings."
    }},
    {{
      "title": "🏛️ Government Schemes & Subsidies",
      "content": "All applicable schemes: PMAY eligibility with exact subsidy amount, CLSS benefit calculation, any other schemes. State exact rupee benefit from each scheme."
    }},
    {{
      "title": "📋 Document Checklist & Application Process",
      "content": "Complete numbered list of required documents with details. Step-by-step application process. Expected timeline. What to prepare before visiting the bank."
    }},
    {{
      "title": "✅ Action Plan",
      "content": "Numbered priority-ordered action steps specific to THIS loan application. Include specific bank names, amounts, deadlines. Make it a ready-to-execute checklist."
    }}
  ]
}}

Be extremely specific — use exact numbers, rates, bank names, and rupee amounts from the conversation.
Return ONLY valid JSON."""

    elif report_class == "policy":
        # ── Policy/Scheme Report ──────────────────────────────────────────────
        return f"""You are an Indian government housing/financial scheme expert writing an eligibility assessment report.

USER PROFILE: {profile_text}
FULL CONVERSATION:
{conv_text}

REPORT FOCUS: {topic}

Write a DETAILED POLICY ELIGIBILITY REPORT with these EXACT sections (return as JSON):
{{
  "title": "Policy Eligibility Report — [{topic}]",
  "sections": [
    {{
      "title": "📋 Eligibility Verdict",
      "content": "Clear ELIGIBLE / NOT ELIGIBLE / PARTIALLY ELIGIBLE verdict for the specific policy/scheme. State the exact benefit amount or subsidy if eligible."
    }},
    {{
      "title": "🔍 Scheme Details & Rules",
      "content": "Comprehensive explanation of the scheme: what it is, who it's for, income limits, property limits, geographic coverage, key conditions."
    }},
    {{
      "title": "✅ User's Eligibility Breakdown",
      "content": "Point-by-point analysis of each eligibility criterion against the user's profile: income check, location check, property ownership check, age check, etc. Tick or cross each criterion with the user's actual values."
    }},
    {{
      "title": "💰 Financial Benefit Calculation",
      "content": "Exact rupee calculation of the benefit. Interest subsidy in rupees. EMI reduction. Total savings over loan tenure. NPV of the subsidy."
    }},
    {{
      "title": "📝 Application Process & Documents",
      "content": "Step-by-step process to apply for this scheme. Required documents. Which banks/institutions to approach. Official portals and links."
    }},
    {{
      "title": "⚠️ Important Conditions & Pitfalls",
      "content": "Key conditions to remain eligible. Common reasons for rejection. What NOT to do. Timelines and deadlines."
    }},
    {{
      "title": "✅ Action Plan",
      "content": "Priority-ordered numbered steps to actually apply and benefit from this scheme."
    }}
  ]
}}

Use exact rupee amounts, percentages, income limits from official PMAY/MUDRA/RBI guidelines.
Return ONLY valid JSON."""

    else:
        # ── General Conversation Report ───────────────────────────────────────
        return f"""You are compiling a financial advisory session report.

USER PROFILE: {profile_text}
FULL CONVERSATION:
{conv_text}

Write a COMPREHENSIVE SESSION SUMMARY REPORT with these EXACT sections (return as JSON):
{{
  "title": "Financial Advisory Session Report — {datetime.now(timezone.utc).strftime('%B %d, %Y')}",
  "sections": [
    {{
      "title": "📌 Session Overview",
      "content": "What was discussed in this session. Key questions asked. Main advice given. Outcomes."
    }},
    {{
      "title": "💼 Financial Profile Summary",
      "content": "Comprehensive analysis of the user's financial position: income, credit, employment, existing obligations, DTI. Strengths and areas for improvement."
    }},
    {{
      "title": "💬 Detailed Q&A Summary",
      "content": "Go through EACH USER question and the advisor's response. Summarize every exchange with the key insight. Include all specific numbers, rates, and figures mentioned."
    }},
    {{
      "title": "🔍 Key Findings",
      "content": "Most important insights from the session: loan eligibility status, rates discussed, schemes eligible for, credit assessment, important warnings or red flags."
    }},
    {{
      "title": "✅ Recommended Next Steps",
      "content": "Priority-ordered numbered action items. Specific, concrete, actionable. Include bank names, amounts, deadlines where applicable."
    }}
  ]
}}

Be extremely detailed. Include every number, rate, scheme name mentioned in the conversation.
Return ONLY valid JSON."""


def _llm_compile_report(history: list, profile: dict, topic: str | None,
                         state: dict) -> dict:
    """Use Groq to build a topic-specific structured report."""
    conv_text = "\n".join(
        f"{'USER' if m['role']=='user' else 'ADVISOR'}: {m['content'][:1000]}"
        for m in history
    ) or "(No conversation history)"

    profile_text = (
        f"Name: {profile.get('full_name','N/A')} | "
        f"Income: ₹{profile.get('annual_income',0):,.0f}/yr | "
        f"Credit Score: {profile.get('credit_score','N/A')} | "
        f"Employment: {profile.get('employment_months','N/A')} months | "
        f"Existing EMI: ₹{profile.get('existing_emi_amount',0):,.0f}/mo | "
        f"City: {profile.get('city','N/A')} | Age: {profile.get('age','N/A')}"
    ) if profile.get("annual_income") else "Profile incomplete"

    # Enrich with live agent outputs
    state_extras = ""
    if state.get("credit_profile"):
        cp = state["credit_profile"]
        state_extras += (
            f"\nCREDIT ANALYSIS: Risk={cp.get('risk_tier')} | "
            f"DTI={cp.get('dti_ratio')}% | Eligible={cp.get('eligible')} | "
            f"Max EMI=₹{cp.get('max_emi_capacity',0):,.0f}/mo"
        )
    if state.get("loan_advisory"):
        la = state["loan_advisory"]
        if la.get("products"):
            for p in la["products"]:
                state_extras += (
                    f"\nLOAN OPTION: {p.get('bank')} | Rate={p.get('rate')}% | "
                    f"EMI=₹{p.get('emi',0):,.0f}/mo | Tenure={p.get('tenure_months')}mo"
                )
        state_extras += f"\nRECOMMENDATION: {la.get('recommendation','')}"
    if state.get("compliance_result"):
        cr = state["compliance_result"]
        state_extras += (
            f"\nCOMPLIANCE: Eligibility={cr.get('eligibility')} | "
            f"Approval Likelihood={cr.get('approval_likelihood')}%"
        )
        if cr.get("scheme_eligibility"):
            for scheme, status in cr["scheme_eligibility"].items():
                state_extras += f"\nSCHEME: {scheme} → {status}"
        if cr.get("required_documents"):
            state_extras += f"\nDOCUMENTS: {', '.join(cr['required_documents'][:6])}"

    # Classify topic type → select prompt template
    report_class = _classify_topic(topic)
    log_action(logger, "info", "report_compiler", "REPORT_CLASS",
               f"topic={topic!r} | class={report_class}")

    prompt = _build_prompt(conv_text, profile_text, state_extras, topic, report_class)

    try:
        from groq import Groq
        client = Groq(api_key=settings.GROQ_API_KEY)
        resp = client.chat.completions.create(
            model="llama-3.3-70b-versatile",
            messages=[{"role": "user", "content": prompt}],
            max_tokens=3000,
            temperature=0.2,
            response_format={"type": "json_object"},
        )
        return json.loads(resp.choices[0].message.content)
    except Exception as e:
        log_action(logger, "warning", "report_compiler", "LLM_FALLBACK", str(e))
        return {
            "title": f"Financial Advisory Report — {topic or 'Session Summary'}",
            "sections": [
                {"title": "Session Summary",
                 "content": f"Session with {len(history)} exchanges.\nProfile: {profile_text}"},
                {"title": "Conversation",
                 "content": conv_text[:2000]},
                {"title": "State Data", "content": state_extras or "No agent data available"},
                {"title": "Next Steps",
                 "content": "Please consult with a financial advisor for detailed guidance."},
            ]
        }



# ─── Main Entry Point ─────────────────────────────────────────────────────────
def compile_and_send_report(state: dict) -> dict:
    """Compile full report, generate PDF, send email."""
    history  = state.get("conversation_history", []) or []
    profile  = state.get("user_profile", {}) or {}
    topic    = state.get("report_topic")
    email    = profile.get("email", "")
    name     = profile.get("full_name", "User")

    if not email:
        return {"message": "⚠️ No verified email on record. Please update your profile with an email address."}

    log_action(logger, "info", "report_compiler", "COMPILING",
               f"user={name} | email={email} | topic={topic} | history_len={len(history)}")

    # 1. Compile via LLM
    report = _llm_compile_report(history, profile, topic, state)

    # 2. Build HTML
    html = _build_html(report, profile)

    # 3. Generate PDF
    try:
        pdf_bytes = _generate_pdf(report, profile)
        pdf_filename = f"loan_advisor_report_{datetime.now().strftime('%Y%m%d_%H%M')}.pdf"
    except Exception as e:
        log_action(logger, "warning", "report_compiler", "PDF_FAILED", str(e))
        pdf_bytes, pdf_filename = None, None

    # 4. Send email
    from email_service import send_report_email
    title = report.get("title", "Financial Advisory Report")
    subject = f"📊 {title} — AI Loan Advisor"
    sent = send_report_email(email, name, subject, html, pdf_bytes, pdf_filename)

    if sent:
        msg = (f"✅ Report **\"{title}\"** sent to **{email}**!\n\n"
               f"📎 A detailed PDF copy is attached to the email.\n"
               f"Check your inbox (and spam folder if not visible).")
    else:
        msg = ("⚠️ Report compiled but email delivery failed. "
               "Please check your email settings.")

    log_action(logger, "info", "report_compiler", "REPORT_SENT",
               f"email={email} | sections={len(report.get('sections', []))} | pdf={bool(pdf_bytes)}")
    return {"message": msg, "report_title": title}
